=== aertslab/SCope/docs/scope-json-metadata.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://github.com/aertslab/SCope/scope-json-metadata.schema",
    "title": "SCope metadata",
    "description": "The metadata stored in a SCope compatible loom file",
    "type": "object",
    "properties": {
        "embeddings": {
            "description": "List of all embeddings stored in the loom file, must contain one entry for -1",
            "type": "array",
            "items": {
                "type": "object",
                "minProperties": 1,
                "properties": {
                    "id": {
                        "type": "integer",
                        "description": "Index of embeddings matrix in Embeddings_X and Embeddings_Y. -1 is special case and is stored in Embedding",
                        "minimum": -1
                    },
                    "name": {
                        "type": "string",
                        "description": "Name shown in SCope"
                    }
                },
                "required": ["id", "name"]
            }
        },
        "clusterings": {
            "description": "List of all clusterings stored in the loom file. Each element in the array is a different clustering (i.e. Louvain at different resolutions).",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "description": "Index of clustering used throughout this loom file",
                        "minimum": 0
                    },
                    "group": {
                        "type": "string",
                        "description": "TODO"
                    },
                    "name": {
                        "type": "string",
                        "description": "Name of clustering displayed in SCope"
                    },
                    "clusters": {
                        "type": "array",
                        "description": "Array of id -> name links for clusters",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "integer",
                                    "description": "Index of cluster within this clustering",
                                    "minimum": 0
                                },
                                "description": {
                                    "type": "string",
                                    "description": "Name of the cluster displayed in SCope"
                                },
                                "cell_type_annotation": {
                                    "type": "array",
                                    "description": "Possible annotations for the cluster",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "data": {
                                                "type": "object",
                                                "description": "Actual data for the annotation",
                                                "properties": {
                                                    "curator_name": {
                                                        "type": "string",
                                                        "description": "Real name of the curator or tool"
                                                    },
                                                    "curator_id": {
                                                        "type": "string",
                                                        "description": "ORCID ID of the curator or version number of the tool"
                                                    },
                                                    "timestamp": {
                                                        "type": "integer",
                                                        "description": "timestamp"
                                                    },
                                                    "obo_id": {
                                                        "type": "string",
                                                        "description": "Controlled vocabulary term"
                                                    },
                                                    "ols_iri": {
                                                        "type": "string",
                                                        "description": "Optional URL linking to vocabulary"
                                                    },
                                                    "annotation_label": {
                                                        "type": "string",
                                                        "description": "Vocabulary name or free text annotation"
                                                    },
                                                    "markers": {
                                                        "type": "array",
                                                        "description": "markers",
                                                        "items": {
                                                            "type": "string"
                                                        }
                                                    },
                                                    "publication": {
                                                        "type": "string",
                                                        "description": "Related publication DOI (Full URL)"
                                                    },
                                                    "comment": {
                                                        "type": "string",
                                                        "description": "Free text comment"
                                                    }
                                                },
                                                "required": [
                                                    "curator_name",
                                                    "curator_id",
                                                    "timestamp",
                                                    "obo_id",
                                                    "ols_iri",
                                                    "annotation_label",
                                                    "markers",
                                                    "publication",
                                                    "comment"
                                                ]
                                            },
                                            "validate_hash": {
                                                "type": "string",
                                                "description": "SHA256 hash of annotation data + salt"
                                            },
                                            "votes": {
                                                "type": "object",
                                                "description": "Vote information for this annotation",
                                                "properties": {
                                                    "votes_for": {
                                                        "type": "object",
                                                        "description": "Data for positive votes",
                                                        "properties": {
                                                            "total": {
                                                                "type": "integer",
                                                                "description": "Number of total votes"
                                                            },
                                                            "voters": {
                                                                "type": "array",
                                                                "description": "Array of voter information",
                                                                "items": {
                                                                    "type": "object",
                                                                    "description": "Information about voters",
                                                                    "properties": {
                                                                        "voter_name": {
                                                                            "type": "string",
                                                                            "description": "Real name of voter"
                                                                        },
                                                                        "voter_id": {
                                                                            "type": "string",
                                                                            "description": "ORCID ID of voter"
                                                                        },
                                                                        "voter_hash": {
                                                                            "type": "string",
                                                                            "description": "SHA256 hash of data + ORCID ID + salt"
                                                                        }
                                                                    },
                                                                    "required": ["voter_name", "voter_id", "voter_hash"]
                                                                }
                                                            }
                                                        },
                                                        "required": ["voters"]
                                                    },
                                                    "votes_against": {
                                                        "type": "object",
                                                        "description": "Data for negative votes",
                                                        "properties": {
                                                            "total": {
                                                                "type": "integer",
                                                                "description": "Number of total votes"
                                                            },
                                                            "voters": {
                                                                "type": "array",
                                                                "description": "Array of voter information",
                                                                "items": {
                                                                    "type": "object",
                                                                    "description": "Information about voters",
                                                                    "properties": {
                                                                        "voter_name": {
                                                                            "type": "string",
                                                                            "description": "Real name of voter"
                                                                        },
                                                                        "voter_id": {
                                                                            "type": "string",
                                                                            "description": "ORCID ID of voter"
                                                                        },
                                                                        "voter_hash": {
                                                                            "type": "string",
                                                                            "description": "SHA256 hash of data + ORCID ID + salt"
                                                                        }
                                                                    },
                                                                    "required": ["voter_name", "voter_id", "voter_hash"]
                                                                }
                                                            }
                                                        },
                                                        "required": ["voters"]
                                                    }
                                                },
                                                "required": ["votes_for", "votes_against"]
                                            }
                                        },
                                        "required": ["data", "validate_hash", "votes"]       
                                    }
                                }
                            },
                            "required": ["id", "description"]
                        }
                    },
                    "clusterMarkerMetrics": {
                        "type": "array",
                        "description": "List of different metrics available from the clustering. Shown in the table in the right sidebar of SCope",
                        "items": {
                            "type": "object",
                            "properties": {
                                "accessor": {
                                    "type": "string",
                                    "description": "Variable name stored in row attributes"
                                },
                                "name": {
                                    "type": "string",
                                    "description": "Name of metric"
                                },
                                "description": {
                                    "type": "string",
                                    "description": "Description of metric"
                                }
                            },
                            "required": ["accessor", "name", "description"]
                        }
                    }
                },
                "required": ["id", "name"]
            }
        },
        "regulonThresholds": {
            "type": "array",
            "description": "List of thresholds generated form SCENIC per regulon",
            "items": {
                "type": "object",
                "properties": {
                    "regulon": {
                        "type": "string",
                        "description": "Name of regulon"
                    },
                    "defaultThresholdValue": {
                        "type": "number",
                        "minimum": 0,
                        "description": "Value of the default threshold"
                    },
                    "defaultThresholdName": {
                        "type": "string",
                        "description": "Name of the default threshold"
                    },
                    "allThresholds": {
                        "type": "object",
                        "uniqueItems": true,
                        "additionalProperties": {
                            "type": "number"
                        }
                    },
                    "motifData": {
                        "type": "string",
                        "description": "Filename for the motif logo"
                    },
                    "motifVersion": {
                        "type": "string",
                        "description": "Version for the motif logo",
                        "enum": ["V8", "V9"]
                    }                                
                },
                "required": ["regulon", "defaultThresholdName", "defaultThresholdValue"]
            }
        },
        "annotations": {
            "type": "array",
            "description": "List of annotations visible in scope",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Name of the annotation"
                    },
                    "values": {
                        "type": "array",
                        "description": "A unique set of the values of the annotation",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": ["name", "values"]
            }
        },
        "metrics": {
            "type": "array",
            "description": "A list of the metrics viewable (column attributes)",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Name of the column attribute to enable colouring of"
                    }
                },
                "required": ["name"]
            }
        }
    },
    "required": ["embeddings"]
}

=== aertslab/SCope/docs/scope-json-metadata.test.json
{
    "embeddings": [{
        "id": -1,
        "name": "SCENIC 25PC, 60 perplexity"
    }, {
        "id": 0,
        "name": "Seurat 82PC, 30 perplexity"
    }],
    "clusterings": [{
        "id": 0,
        "group": "Seurat",
        "name": "Seurat resolution 2.0",
        "clusters": [{
            "id": 0,
            "description": "Mushroom Body (1)",
            "cell_type_annotation": [{
                "data": {
                    "curator_name": "Kristofer Davie",
                    "curator_id": "0000-0003-2182-1249",
                    "timestamp": 1581609997591,
                    "obo_id": "GO:0043005",
                    "ols_iri": "http://purl.obolibrary.org/obo/GO_0043005",
                    "annotation_label": "neuron projection",
                    "markers": ["ey"],
                    "publication": "https://doi.org/10.1016/j.cell.2018.05.057",
                    "comment": "This cluster seems to be enriched in neuronal projection genes"},
               "validate_hash": "3070ff3f9913cda19183bc74e310c61e675540b9f52a6d4d1724919e744d363a",
               "votes": {
                   "votes_for": {
                       "total": 0, 
                       "voters": []},
                    "votes_against": {
                        "total": 1,
                    "voters": [{
                        "voter_name": "Kristofer Davie",
                        "voter_id": "0000-0003-2182-1249",
                        "voter_hash": "de4787fba14bb1f412bd33055f6ca155172bba34b4b88ef0662ad58b823a06de"}
                        ]
                    }
                }
            }]
        }],
        "clusterMarkerMetrics": [{
           "accessor": "avg_logFC", 
           "name": "Avg. logFC",
           "description": "Average log fold change from Wilcox test (Seurat)"  
        }]
    }],
    "regulonThresholds": [{
        "regulon": "Abd-B_(17g)",
        "defaultThresholdValue": 0.00909688,
        "defaultThresholdName": "tenPercentOfMax",
        "allThresholds": {
              "tenPercentOfMax": 0.00909688
        },
        "motifData": "idmmpmm__Abd-B.png",
        "motifVersion": "V8"
    }],
    "annotations": [{
        "name": "Genotype",
        "values": [
            "W1118",
            "DGRP-551"
        ]
    }],
    "metrics": [{
        "name": "nUMI"
    }, {
        "name": "nGene"
    }]
}
